In [11]:
import numpy as np

In [12]:
# Array Range = arange

array = np.arange(100)
array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [13]:
# Simple Range = range

my_List = list(range(100))
print(my_List)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99]


In [14]:
type(array)

numpy.ndarray

In [16]:
type(my_List)

list

In [17]:
array.dtype

dtype('int64')

In [19]:
for _ in range(10) : array2 = array * 2
array2

array([  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,
        26,  28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,
        52,  54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,
        78,  80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100, 102,
       104, 106, 108, 110, 112, 114, 116, 118, 120, 122, 124, 126, 128,
       130, 132, 134, 136, 138, 140, 142, 144, 146, 148, 150, 152, 154,
       156, 158, 160, 162, 164, 166, 168, 170, 172, 174, 176, 178, 180,
       182, 184, 186, 188, 190, 192, 194, 196, 198])

In [20]:
for _ in range(10) : my_List = [i * 2 for i in my_List]
print(my_List)

[0, 1024, 2048, 3072, 4096, 5120, 6144, 7168, 8192, 9216, 10240, 11264, 12288, 13312, 14336, 15360, 16384, 17408, 18432, 19456, 20480, 21504, 22528, 23552, 24576, 25600, 26624, 27648, 28672, 29696, 30720, 31744, 32768, 33792, 34816, 35840, 36864, 37888, 38912, 39936, 40960, 41984, 43008, 44032, 45056, 46080, 47104, 48128, 49152, 50176, 51200, 52224, 53248, 54272, 55296, 56320, 57344, 58368, 59392, 60416, 61440, 62464, 63488, 64512, 65536, 66560, 67584, 68608, 69632, 70656, 71680, 72704, 73728, 74752, 75776, 76800, 77824, 78848, 79872, 80896, 81920, 82944, 83968, 84992, 86016, 87040, 88064, 89088, 90112, 91136, 92160, 93184, 94208, 95232, 96256, 97280, 98304, 99328, 100352, 101376]


In [21]:
num = np.random.randn(2, 7)
num

array([[ 1.64129145,  0.91878836,  1.1831057 , -1.1280986 ,  0.28174439,
        -1.35552835,  0.07110278],
       [ 0.46100391,  1.16593832,  0.08150379, -0.62913866,  1.20629456,
        -0.390574  ,  0.2452578 ]])

In [22]:
num*3

array([[ 4.92387434,  2.75636507,  3.5493171 , -3.38429581,  0.84523318,
        -4.06658504,  0.21330835],
       [ 1.38301174,  3.49781496,  0.24451136, -1.88741597,  3.61888368,
        -1.171722  ,  0.7357734 ]])

In [23]:
arr = np.arange(49).reshape(7, 7)
arr

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39, 40, 41],
       [42, 43, 44, 45, 46, 47, 48]])

In [24]:
arr.shape

(7, 7)

In [25]:
arr.ndim

2

In [26]:
arr3d = arr.reshape(7, 1, 7)
arr3d

array([[[ 0,  1,  2,  3,  4,  5,  6]],

       [[ 7,  8,  9, 10, 11, 12, 13]],

       [[14, 15, 16, 17, 18, 19, 20]],

       [[21, 22, 23, 24, 25, 26, 27]],

       [[28, 29, 30, 31, 32, 33, 34]],

       [[35, 36, 37, 38, 39, 40, 41]],

       [[42, 43, 44, 45, 46, 47, 48]]])

In [27]:
arr = np.zeros_like(arr3d)
arr

array([[[0, 0, 0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0, 0, 0]]])

In [28]:
arr = np.zeros(3)
arr

array([0., 0., 0.])

In [29]:
arr = np.zeros((2,3))
arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [30]:
data = np.ones(10)
data

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [31]:
data = np.ones((4,5))
data

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [32]:
data = np.ones_like(arr3d)
data

array([[[1, 1, 1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1, 1, 1]]])

In [34]:
matrix = np.full(5,8)
matrix

array([8, 8, 8, 8, 8])

In [35]:
matrix = np.full((7,4), 9)
matrix

array([[9, 9, 9, 9],
       [9, 9, 9, 9],
       [9, 9, 9, 9],
       [9, 9, 9, 9],
       [9, 9, 9, 9],
       [9, 9, 9, 9],
       [9, 9, 9, 9]])

In [36]:
matrix = np.eye(5)
matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [37]:
matrix = np.eye(4, 4)
matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [38]:
my_List = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
my_List

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [39]:
my_List[2,1]

8

In [40]:
n1 = np.arange(36).reshape(6, 6)
n1

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [41]:
n1 = np.arange(36).reshape(6, 6)
n2 = np.arange(36).reshape(6, 6)

n1 * n2

array([[   0,    1,    4,    9,   16,   25],
       [  36,   49,   64,   81,  100,  121],
       [ 144,  169,  196,  225,  256,  289],
       [ 324,  361,  400,  441,  484,  529],
       [ 576,  625,  676,  729,  784,  841],
       [ 900,  961, 1024, 1089, 1156, 1225]])

In [42]:
n1 @ n2

array([[ 330,  345,  360,  375,  390,  405],
       [ 870,  921,  972, 1023, 1074, 1125],
       [1410, 1497, 1584, 1671, 1758, 1845],
       [1950, 2073, 2196, 2319, 2442, 2565],
       [2490, 2649, 2808, 2967, 3126, 3285],
       [3030, 3225, 3420, 3615, 3810, 4005]])

# **NumPy Array Basic Indexing And Slicing**

In [43]:
import numpy as np

In [44]:
arr2d = np.arange(49).reshape(7, 7)
arr2d

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39, 40, 41],
       [42, 43, 44, 45, 46, 47, 48]])

In [45]:
arr2d[2,6]

20

In [46]:
arr2d[5][5]

40

In [47]:
arr3d = np.arange(120).reshape(2, 10, 6)
arr3d

array([[[  0,   1,   2,   3,   4,   5],
        [  6,   7,   8,   9,  10,  11],
        [ 12,  13,  14,  15,  16,  17],
        [ 18,  19,  20,  21,  22,  23],
        [ 24,  25,  26,  27,  28,  29],
        [ 30,  31,  32,  33,  34,  35],
        [ 36,  37,  38,  39,  40,  41],
        [ 42,  43,  44,  45,  46,  47],
        [ 48,  49,  50,  51,  52,  53],
        [ 54,  55,  56,  57,  58,  59]],

       [[ 60,  61,  62,  63,  64,  65],
        [ 66,  67,  68,  69,  70,  71],
        [ 72,  73,  74,  75,  76,  77],
        [ 78,  79,  80,  81,  82,  83],
        [ 84,  85,  86,  87,  88,  89],
        [ 90,  91,  92,  93,  94,  95],
        [ 96,  97,  98,  99, 100, 101],
        [102, 103, 104, 105, 106, 107],
        [108, 109, 110, 111, 112, 113],
        [114, 115, 116, 117, 118, 119]]])

In [48]:
arr3d = np.arange(15)
arr3d

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [50]:
sliced = arr3d[2:5:2]
sliced

array([2, 4])

In [59]:
sliced = arr3d[-4:-1:2]
sliced

array([11, 13])

In [63]:
array1 = np.arange(32).reshape(8, 4)
array1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [64]:
array1[2:5,1:3]
array1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])